const orderTypes = {
  ORDER_APPROVED: "ORDER_APPROVED",
  ORDER_MISSING: "ORDER_MISSING",
  ORDER_MISSING_URGENT: "ORDER_MISSING_URGENT",
  ORDER_DETAILS_CHANGE: "ORDER_DETAILS_CHANGE",
  SET_ORDER_DETAILS: 'SET_ORDER_DETAILS'
};

export default orderTypes;
